# SPDX-FileCopyrightText: 2022 The Go-SSB Authors
# SPDX-License-Identifier: MIT

before:
  hooks:
    - go mod tidy

builds:
  - id: go-ssb
    dir: cmd/go-sbot
    binary: go-ssb
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

  - id: go-ssb-lite
    dir: cmd/go-sbot
    binary: go-ssb-lite
    flags:
      - -tags=lite
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

  - id: sbotcli
    dir: cmd/sbotcli
    binary: sbotcli
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

archives:
  - id: go-ssb
    format: binary

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
