name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Node for interop testing
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build smoke test
      run: go build -v ./cmd/go-sbot

    - name: install node ssb-stack
      run: |
        pushd message/legacy
        npm ci
        popd
        pushd tests
        npm ci
        popd

    - name: Test
      run: make test
      env:
        RUNNING_ON_CI: YES
